name: Build CLI

on:
  push:
    branches:                                                                                                                                                                    â”‚
      - '**'
    tags:
      - 'cli-v*'

jobs:
  build-cli:
    name: Build CLI on ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - os: linux
            arch: x86_64
            runs-on: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            executable-name: clickr-cli
            artifact-name: clickr-linux-x86_64
          - os: windows
            arch: x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc
            executable-name: clickr-cli.exe
            artifact-name: clickr-windows-x86_64
          - os: macos
            arch: arm64
            runs-on: macos-14
            target: aarch64-apple-darwin
            executable-name: clickr-cli
            artifact-name: clickr-macos-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build CLI (Release)
        working-directory: ./cli
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: cli/target/${{ matrix.target }}/release/${{ matrix.executable-name }}


  release:
    name: Create GitHub Release
    if: startsWith(github.ref, 'refs/tags/cli-v')
    runs-on: ubuntu-latest
    needs: build-cli
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Prepare release assets
        run: |
          mkdir release
          mv artifacts/clickr-linux-x86_64/clickr-cli release/clickr-linux-x86_64
          mv artifacts/clickr-windows-x86_64/clickr-cli.exe release/clickr-windows-x86_64.exe
          mv artifacts/clickr-macos-arm64/clickr-cli release/clickr-macos-arm64
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*
